#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include "raylib.h"

#define SCREEN_HEIGHT 1000
#define SCREEN_WIDTH 1600

#define MAP_WIDTH 16
#define MAP_HEIGHT 16

#define MINIMAP_SCALE 10
#define MINIMAP_OFFSET_X (SCREEN_WIDTH - MINIMAP_SCALE * MAP_WIDTH)
#define MINIMAP_OFFSET_Y 0 

#define PLAYER_MOVEMENT_SPEED (1.0f / 20.0f)
#define PLAYER_ROTATION_SPEED (3 * DEG2RAD)
#define PLAYER_FOV 60 * DEG2RAD
#define PLAYER_MOVEMENT_SPEED_SPRINT_LIMIT (1.8f / 20.0f)

#define NEARBLACK CLITERAL(Color){15,15,15,255}
#define FLOOR_COLOR BEIGE
#define CEILING_COLOR SKYBLUE
#define SHADOW_POWER (1.0f/100.0f)

#define TEXT_COLOR BLACK

#define TILE_BUFFER_SIZE 16

#endif